echo "Langue - Language :
1) Français
2) English"
echo -n "Votre choix | Your choice: "
read lang
if [ $lang = 1 ] && [ -n $lang ]; then
lang=("Bienvenue dans le générateur de fichier HTML par Exybore !" "Nom du fichier (par défaut: index.html): " "Titre: " "Votre fichier a bien été généré dans $PWD !")
locale="fr"
else
lang=("Welcome to the HTML file generator by Exybore !" "File name (default: index.html): " "Title: " "Your file has been generated in $PWD !")
locale="en"
fi
echo ${lang[0]}
echo -n ${lang[1]}
read file
if [ -z $file ]
then
file="index.html"
fi
echo -n ${lang[2]}
read title
if [ -n $title ]; then
title_meta="<meta property=\"og:title\" content=\"$title\" />"
else
  title_meta=""
fi
echo '' >> $file
echo "<!--
  File was generated by Exybore's HTML generator 0.1
  https://github.com/Exybore/sh-html-generator
  Contact: @exybore on Twitter | @Exybore@mstdn.io on Mastodon
-->
<!DOCTYPE html>
<html lang=\"$locale\">
<head>
  <title>$title</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  $title_meta
</head>
<body>

</body>
</html>" >> $file
echo ${lang[3]}
